#!/usr/bin/env bash
#This script will print on numbers that multiple of 3 and 5
for i in {1..100}
do
	if ( i%15 ==0 )
	  echo "FizzBuzz"
		
 : ' elif ( i%3 ==0 )
	   echo "Fizz"
		
   elif ( i%5 ==0 )
	   echo "Buzz" '
  fi
	   ((i++))
done

