#!/usr/bin/env bash
#Thi script will display bad luck in 4 and is your chance in 8
i=1
while [ $i -le 10 ]
do
if [[ $i == '4' ]];then
  echo bad luck
elif [[ $i == '8' ]];then
  echo good luck
else 
  echo Best School
fi
((i++))
done
