#!/usr/bin/env bash
#This script will write sfter line 4,9 and 17 using case statement
i=1
while [ $i -le 20 ]
do
case $i in
	5)
	   echo "bad luck from China"
		echo $i;;
	10)
		echo "bad luck from Japan"
		echo $i;;
	18)
		echo "bad luck from Italy"
		echo $i;;
	*)
		echo $i;;
              esac
		((i++))
done
