#!/usr/bin/env bash
#This script will write sfter line 4,9 and 17 using case statement
i=1
while [ $i -le 20 ]
do
echo "$i"
i=$((i+1))
case $i in
	"$i" == "4")
		echo bad luck from China
		;;
	"$i" == "9")
		echo bad luck from Japan
		;;
	"$i" == "17")
		echo bad luck from Italy
		;;
	esac
done
